# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7403564fbd2d4f2c1032b8b08c7dc4369640d5874ebd850f9356ca9f9a54658c0399a39c71d8d273e960d95a84f7c272d8680a2d3e4f26775ad6f6f97435e450

  # stripe
  stripe_publishable_key: pk_test_
  stripe_secret_key: sk_test_

test:
  secret_key_base: 1ddafa16ec26e8a7a3331a0532af0ecba044051a4a81cb60b68af4dd029ea70b076b5a0752cec3b8ab1e830ae9e937e187793606816e7bb0dbf660bcd56368c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>